services:
  db:
    image: postgres:17-alpine
    container_name: hjv-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - hjv_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    init: true
    build:
      context: .
      dockerfile: apps/api/DockerFile

    container_name: hjv-api
    restart: unless-stopped

    working_dir: /workspace/apps/api

    env_file:
      - "./apps/api/.env"

    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:5555:5555"

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./apps/api/prisma:/workspace/apps/api/prisma
      - ./apps/api/generated:/workspace/apps/api/generated
      - ./apps/api/prisma.config.ts:/workspace/apps/api/prisma.config.ts

    develop:
      watch:
        - action: sync+restart
          path: ./apps/api/src
          target: /workspace/apps/api/src
          initial_sync: true

        - action: rebuild
          path: ./apps/api/package.json

        - action: rebuild
          path: ./pnpm-lock.yaml

        - action: rebuild
          path: ./pnpm-workspace.yaml


volumes:
  hjv_postgres_data: