services:
  postgres:
    image: postgres:17
    container_name: hjv-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hjv_user
      POSTGRES_PASSWORD: hjv_password
      POSTGRES_DB: hjv_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: