FROM node:22-bookworm-slim

RUN apt-get update -y \
    && apt-get install -y openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN corepack enable

WORKDIR /workspace

COPY . .

RUN pnpm install --filter ./apps/api... --frozen-lockfile

WORKDIR /workspace/apps/api

EXPOSE 3000

CMD ["sh", "-c", "pnpm prisma generate && pnpm start:dev"]